version: "3.9" 
services:
   db:
     image: mongo:latest
     container_name: some-mongo
     volumes:
       - lemon:/data/db
     restart: always
     networks: 
        - lemoncode-challenge
   back:
     depends_on:
       - db
     build: ./backend
     container_name: topics-api
     restart: always
     networks: 
       - lemoncode-challenge
   front:
     depends_on:
       - back
     build: ./frontend
     container_name: myfront
     ports:
       - "8080:3000"
     restart: always
     environment:
       API_URI: http://topics-api:5000/api/topics
     networks: 
       - lemoncode-challenge       
volumes:
    lemon: 
networks:
    lemoncode-challenge: 